### PR TITLE
Update SAUVC 2024 organizers.yml

### PR DESCRIPTION
**Pull request by esthertanhj**
I would need @notthetup 's help to do a final review and merging of the list onto the webpage.

### CODE REVIEW

**Review by harivnkochi — APPROVED** [review]
I added a few changes here and there. Looks good.

**Comment by notthetup** [comment]
Thanks @esthertanhj.

I think some of the photos need a bit of massaging of the aspect ratio. I think the CSS style requires the photos to be equal in height and width.

Screenshot 2024-06-20 at 11 09 14 AM

**Comment by esthertanhj** [comment]
> Thanks @esthertanhj.
> 
> I think some of the photos need a bit of massaging of the aspect ratio. I think the CSS style requires the photos to be equal in height and width.
> 
> Screenshot 2024-06-20 at 11 09 14 AM

Oops I see. Let me work on updating the images.

**Comment by esthertanhj** [comment]
Ok I have fixed the images @notthetup ! Please let me know if there are still any errors with any of them.

**Comment by notthetup** [comment]
All good.

**Review by notthetup — APPROVED** [review]

**Comment by esthertanhj** [comment]
Thanks @notthetup , I just merged the branch. May I know where on the webpage it gets updated on?

**Comment by notthetup** [comment]
It should update automatically once this action completes https://github.com/sauvc/sauvc.github.io/actions/runs/9591804380

**Comment by esthertanhj** [comment]
> It should update automatically once this action completes https://github.com/sauvc/sauvc.github.io/actions/runs/9591804380

Unfortunately I got this warning even though status shows "success". Does this mean the page did not render correctly due to a lack of dependencies @notthetup ?
Screenshot 2024-06-20 at 1 34 19 PM

**Comment by notthetup** [comment]
We didn't change any Gemfile dependencies. So it shouldn't trigger a new error. I think it's fine, we don't use all the Gem dependencies anyway.

**Comment by esthertanhj** [comment]
> We didn't change any Gemfile dependencies. So it shouldn't trigger a new error. I think it's fine, we don't use all the Gem dependencies anyway.

Ok thanks. Not sure why, but the changes do not show up in the SAUVC webpage.

**Comment by notthetup** [comment]
> > We didn't change any Gemfile dependencies. So it shouldn't trigger a new error. I think it's fine, we don't use all the Gem dependencies anyway.
> 
> Ok thanks. Not sure why, but the changes do not show up in the SAUVC webpage.

Likely cached. It'll take a while for the cache to be purged.

**Pull request merged**
